

export const characters = {
    "rogue" : {
        "name": "rogue",
        "Strength": 1,
        "Dexterity": 4,
        "Stamina": 2,
        "Charisma": 3,
        "Finesse": 3,
        "Composure": 2,
        "Intelligence" : 2,
        "Wits" : 3,
        "Resolve": 2,
        "Athletics":  1,
        "Brawl":  1,
        "Agility":  2,
        "Ranged":  1,
        "Larceny":  3,
        "Stealth":  3,
        "Survival":  0,
        "Melee":  1,
        "Animal ken":  0,
        "Insight":  2,
        "Expression":  0,
        "Intimidation":  0,
        "Persuasion":  2,
        "Etiquette":  0,
        "Streetwise":  2,
        "Subterfuge":  3,
        "Academics":  0,
        "Tech":  1,
        "Finance":  1,
        "Investigation":  2,
        "Medicine":  0,
        "Occult":  0,
        "Politics":  0,
        "Craft":  1,
    },
    "brawler" : {
        "name": "brawler",
        "Strength": 4,
        "Dexterity": 3,
        "Stamina": 3,
        "Charisma": 2,
        "Finesse": 2,
        "Composure": 2,
        "Intelligence" : 1,
        "Wits" : 3,
        "Resolve": 2,
        "Athletics":  4,
        "Brawl":  3,
        "Agility":  3,
        "Ranged":  1,
        "Larceny":  1,
        "Stealth":  1,
        "Survival":  2,
        "Melee":  2,
        "Animal ken":  2,
        "Insight":  1,
        "Expression":  0,
        "Intimidation":  2,
        "Persuasion":  1,
        "Etiquette":  0,
        "Streetwise":  2,
        "Subterfuge":  1,
        "Academics":  0,
        "Tech":  0,
        "Finance":  0,
        "Investigation":  0,
        "Medicine":  1,
        "Occult":  0,
        "Politics":  0,
        "Craft":  1,
    }

}